language: julia
os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7

matrix:
  allow_failures:
    - julia: 0.7

notifications:
  email: false
sudo: false
=======
git:
  depth: 99999999
## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
 allow_failures:
 - julia: nightly
